  name: Delövning 1 - Minimal Pipeline
  
  on: workflow_dispatch
  # ska startas manuellt och om man vill kan lägga det push lägge så startas så fort man har pushat en ny kod
  
  jobs:
    just-example: 
      runs-on: ubuntu-latest 
      steps:
        - name: show the pipeline started # namnge steget
          run: echo "Pipeline har startat"
        - name: show Python version
          run: python --version # vad som ska göras