name: Delövning 3 - Artifacts

on:
  workflow_dispatch:

jobs:
  create-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Skapar log.txt
        run: echo "skapats av Nasir" > log.txt # 1. skapa filen
      - name: Laddar upp loggfilen som artifact
        uses: action/uppload-artifact@v2 # 2a. vilken action kan användas här? #uppload
        with:
        # 2b. vad heter denna sektion? # sektionen "with" kallas för input parameters
          name: loggfil
          path: log.txt