name: Delövning 4 - Triggers

on: 
  push: # kan använda "pull_request" för att den ska köra när det kommer en pull request i main branch
    branches: 
      - main # när det kommer en commit i main branchen
jobs:
  trigger-test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo info        
        run: echo "Workflow triggat av nya commits" # TODO: uppdatera texten